version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./single:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always

